//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItems
    {
        public int CartItemId { get; set; }
        public string UserId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> FlashSaleProductId { get; set; }
        public Nullable<decimal> LockedPrice { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual FlashSaleProducts FlashSaleProducts { get; set; }
        public virtual Products Products { get; set; }
    }
}
