//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlashSaleProducts
    {
        public FlashSaleProducts()
        {
            this.CartItems = new HashSet<CartItems>();
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int FlashSaleProductId { get; set; }
        public int FlashSaleId { get; set; }
        public int ProductId { get; set; }
        public decimal OriginalPrice { get; set; }
        public decimal SalePrice { get; set; }
        public decimal DiscountPercentage { get; set; }
        public Nullable<int> StockLimit { get; set; }
        public int SoldCount { get; set; }
    
        public virtual ICollection<CartItems> CartItems { get; set; }
        public virtual FlashSales FlashSales { get; set; }
        public virtual Products Products { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}
