//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderItems = new HashSet<OrderItems>();
            this.Payments = new HashSet<Payments>();
        }
    
        public int OrderId { get; set; }
        public string UserId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal Total { get; set; }
        public string TrackingNumber { get; set; }
        public string ShippingAddress { get; set; }
        public string Notes { get; set; }
        public string OrderNumber { get; set; }
        public string OrderStatus { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentStatus { get; set; }
        public string ShippingEmail { get; set; }
        public string ShippingName { get; set; }
        public string ShippingPhone { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
