//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.CartItems = new HashSet<CartItems>();
            this.FlashSaleProducts = new HashSet<FlashSaleProducts>();
            this.OrderItems = new HashSet<OrderItems>();
            this.ProductImages = new HashSet<ProductImages>();
            this.RecentlyViewedProducts = new HashSet<RecentlyViewedProducts>();
            this.Reviews = new HashSet<Reviews>();
            this.WishlistItems = new HashSet<WishlistItems>();
            this.AspNetUsers = new HashSet<AspNetUsers>();
        }
    
        public int ProductId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int Stock { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<CartItems> CartItems { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual ICollection<FlashSaleProducts> FlashSaleProducts { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual ICollection<ProductImages> ProductImages { get; set; }
        public virtual ICollection<RecentlyViewedProducts> RecentlyViewedProducts { get; set; }
        public virtual ICollection<Reviews> Reviews { get; set; }
        public virtual ICollection<WishlistItems> WishlistItems { get; set; }
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
    }
}
