//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishlistItems
    {
        public int WishlistItemId { get; set; }
        public string UserId { get; set; }
        public int ProductId { get; set; }
        public System.DateTime AddedAt { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Products Products { get; set; }
    }
}
